from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch


def generate_pdf_report(
    filename,
    target,
    scan_results,
    recommendations=None
):
    """
    Generate a PDF report containing scan results
    and defensive security recommendations.
    """

    document = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    story = []

    story.append(
        Paragraph("NetScope — Network Scan Report", styles["Title"])
    )
    story.append(Spacer(1, 0.2 * inch))

    story.append(
        Paragraph(f"<b>Target:</b> {target}", styles["Normal"])
    )
    story.append(Spacer(1, 0.15 * inch))

    story.append(
        Paragraph("<b>Scan Results</b>", styles["Heading2"])
    )
    story.append(Spacer(1, 0.1 * inch))

    if scan_results:
        for result in scan_results:
            if isinstance(result, dict):
                port = result.get("port", "Unknown")
                service = result.get("service", "Unknown")
                version = result.get("version", "")
                state = result.get("state", "open")

                text = (
                    f"Port: {port} | State: {state} | "
                    f"Service: {service} | Version: {version}"
                )
            else:
                text = str(result)

            story.append(Paragraph(text, styles["Normal"]))
            story.append(Spacer(1, 0.08 * inch))
    else:
        story.append(
            Paragraph("No open services detected.", styles["Normal"])
        )

    story.append(Spacer(1, 0.2 * inch))

    story.append(
        Paragraph(
            "Defensive Security Recommendations",
            styles["Heading2"]
        )
    )
    story.append(Spacer(1, 0.1 * inch))

    if recommendations:
        for recommendation in recommendations:
            if isinstance(recommendation, dict):
                message = recommendation.get(
                    "message",
                    "No recommendation available."
                )
            else:
                message = str(recommendation)

            story.append(
                Paragraph(f"• {message}", styles["Normal"])
            )
            story.append(Spacer(1, 0.08 * inch))
    else:
        story.append(
            Paragraph(
                "No specific recommendations.",
                styles["Normal"]
            )
        )

    story.append(Spacer(1, 0.25 * inch))

    story.append(
        Paragraph(
            "Generated by NetScope — Local Network Service Reporter",
            styles["Italic"]
        )
    )

    document.build(story)

    return filename